#!/usr/bin/env python3
"""Generate the release-owned first-party Skill publication migration."""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from mercury_tools.catalog.identity import canonical_json
from mercury_tools.skills.catalog import ACCOUNTING_SKILL_CATALOG

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = (
    ROOT / "supabase/migrations/20260731100000_mercury_v1_publish_first_party_skills.sql"
)
_PAYLOAD_DELIMITER = "$mercury_v1_first_party_skill_payload$"


def build_publication_payload() -> tuple[dict[str, Any], ...]:
    """Project every Git-canonical first-party Skill for global publication."""

    return tuple(
        {
            "visibility_scope": "global",
            "tenant_id": None,
            "workspace_id": None,
            "skill_id": skill.skill_id,
            "skill_version": skill.skill_version,
            "publication_status": "published",
            "projection": skill.published_projection(),
            "projection_sha256": skill.projection_sha256,
            "git_source_path": skill.git_source_path,
        }
        for skill in ACCOUNTING_SKILL_CATALOG
    )


def render_publication_migration() -> str:
    """Render an idempotent migration that rejects any projection drift."""

    payload = json.dumps(
        json.loads(canonical_json(build_publication_payload())),
        ensure_ascii=False,
        sort_keys=True,
        indent=2,
        allow_nan=False,
    )
    if _PAYLOAD_DELIMITER in payload:
        raise ValueError("first_party_skill_publication_payload_invalid")

    return f"""\
-- Generated by scripts/build_v1_skill_publication_migration.py.
-- Git is canonical; regenerate this migration instead of editing the payload.
begin;

do $mercury_v1_publish_first_party_skills$
declare
  candidate jsonb;
  existing_count bigint;
  projection_matches boolean;
begin
  for candidate in
    select payload.item
    from jsonb_array_elements(
      {_PAYLOAD_DELIMITER}{payload}{_PAYLOAD_DELIMITER}::jsonb
    ) with ordinality as payload(item, ordinal)
    order by payload.ordinal
  loop
    if jsonb_typeof(candidate) is distinct from 'object'
      or candidate ->> 'visibility_scope' is distinct from 'global'
      or candidate -> 'tenant_id' is distinct from 'null'::jsonb
      or candidate -> 'workspace_id' is distinct from 'null'::jsonb
      or candidate ->> 'publication_status' is distinct from 'published'
      or candidate -> 'projection' ->> 'skill_id'
        is distinct from candidate ->> 'skill_id'
      or candidate -> 'projection' ->> 'skill_version'
        is distinct from candidate ->> 'skill_version'
      or candidate -> 'projection' ->> 'git_source_path'
        is distinct from candidate ->> 'git_source_path'
      or candidate ->> 'projection_sha256' is distinct from encode(
        digest(
          public.mercury_canonical_jsonb(candidate -> 'projection'),
          'sha256'
        ),
        'hex'
      )
    then
      raise exception 'mercury_first_party_skill_publication_payload_invalid';
    end if;

    insert into public.mercury_published_skills (
      visibility_scope,
      tenant_id,
      workspace_id,
      skill_id,
      skill_version,
      publication_status,
      projection,
      projection_sha256,
      git_source_path
    ) values (
      candidate ->> 'visibility_scope',
      nullif(candidate ->> 'tenant_id', '')::uuid,
      nullif(candidate ->> 'workspace_id', '')::uuid,
      candidate ->> 'skill_id',
      candidate ->> 'skill_version',
      candidate ->> 'publication_status',
      candidate -> 'projection',
      candidate ->> 'projection_sha256',
      candidate ->> 'git_source_path'
    )
    on conflict do nothing;

    select
      count(*),
      coalesce(
        bool_and(
          skill.visibility_scope = candidate ->> 'visibility_scope'
          and coalesce(to_jsonb(skill.tenant_id), 'null'::jsonb)
            = candidate -> 'tenant_id'
          and coalesce(to_jsonb(skill.workspace_id), 'null'::jsonb)
            = candidate -> 'workspace_id'
          and skill.skill_id = candidate ->> 'skill_id'
          and skill.skill_version = candidate ->> 'skill_version'
          and skill.publication_status = candidate ->> 'publication_status'
          and skill.projection = candidate -> 'projection'
          and skill.projection_sha256 = candidate ->> 'projection_sha256'
          and skill.git_source_path = candidate ->> 'git_source_path'
        ),
        false
      )
    into existing_count, projection_matches
    from public.mercury_published_skills as skill
    where skill.skill_id = candidate ->> 'skill_id'
      and skill.skill_version = candidate ->> 'skill_version';

    if existing_count <> 1 or not projection_matches then
      raise exception 'mercury_first_party_skill_publication_mismatch';
    end if;
  end loop;
end;
$mercury_v1_publish_first_party_skills$;

commit;
"""


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Build the first-party Skill publication migration."
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when the checked-in migration differs from the catalog.",
    )
    args = parser.parse_args(argv)
    rendered = render_publication_migration()

    if args.check:
        try:
            current = args.output.read_text(encoding="utf-8")
        except OSError:
            print("first-party Skill publication migration is missing", file=sys.stderr)
            return 1
        if current != rendered:
            print("first-party Skill publication migration is stale", file=sys.stderr)
            return 1
        return 0

    args.output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
